### ISSUE TITLE
Options for i18n title for buttons/category/emoji/search... etc.

### ISSUE THREAD

**Issue by Banana-In-Black** [mervick/emojionearea#128]
1) Or an option to disable all these l10n string ?

2) Is there an option to hide search field ?

Thank you.

**Comment by regentropft** [comment]
this is a great feature request. i support it!

**Comment by hacknlove** [comment]
This is my workaround

```css
      .emojionearea-scroll-area {
        .emojionearea-category {
          .emojionearea-category-title {
            display: none;
          }
          &::before {
            display: block;
            font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif;
            font-size: 13px;
            font-weight: normal;
            color: #b2b2b2;
            background: #FFFFFF;
            line-height: 20px;
            margin: 0;
            padding: 7px 0 5px 6px;
          }
        }
        .emojionearea-category[name=recent] {
          &::before {
            content: 'Reciente';
          }
        }
        .emojionearea-category[name=smileys_people] {
          &::before {
            content: 'Caritas';
          }
        }
        .emojionearea-category[name=animals_nature] {
          &::before {
            content: 'Animales y naturaleza';
          }
        }
        .emojionearea-category[name=food_drink] {
          &::before {
            content: 'Comida y bebida';
          }
        }
        .emojionearea-category[name=activity] {
          &::before {
            content: 'Actividades';
          }
        }
        .emojionearea-category[name=travel_places] {
          &::before {
            content: 'Viajes y lugares';
          }
        }
        .emojionearea-category[name=objects] {
          &::before {
            content: 'Objetos';
          }
        }
        .emojionearea-category[name=symbols] {
          &::before {
            content: 'Símbolos';
          }
        }
        .emojionearea-category[name=flags] {
          &::before {
            content: 'Banderas';
          }
        }
        .emojionearea-category[name=tones] {
          &::before {
            content: 'Diversidad';
          }
        }
      }

```
Eventually I am going to need multilingual support, and I will achieve that with some css class 

I will share that too if the properly js solution is not done by then
