### ISSUE TITLE
Size issue with TEXTAREA

### ISSUE THREAD

**Issue by socialltd** [mervick/emojionearea#16]
Is the emoji editor a fixed size [height]? 
I added ROWS to TEXTAREA, and the emoji editor doesnt resize accordingly [in height].

**Comment by socialltd** [comment]
Ok the hack I'm using to achieve this is this..

        $('.emojionearea-editor').height($('#my_textareaid').outerHeight());

**Comment by mervick** [comment]
The easiest way is to use custom stylesheet, something like this:
```css
.emojionearea > .emojionearea-editor {
    min-heght: 500px;
    max-height: 1200px;
    width: 50%;
    // whatever
}
```
