### ISSUE TITLE
Loading display-only emojis

### ISSUE THREAD

**Issue by danielprosser1** [mervick/emojionearea#18]
I have no problem using emojionearea to create emoji **inputs** on textareas like this...

$("#commentsTextArea").emojioneArea({
    tones: false,
    autocomplete: false,
    hidePickerOnBlur: true
  });

But then when I take this input and save the comment to the database and display the result in a normal text element on the page, of course it's up to the browser to try and find a suitable emoji (sometimes they find one but it always looks different).

So I need a way to apply emojionearea to my display-only elements without adding the option to choose new emojis.  Hopefully that makes sense but so far I've found no parameters that would enable me to "display as emojionearea" without adding the picker/selector.

Thanks in advance for any hints!

**Comment by mervick** [comment]
There are different ways to do that.

The easiest way is to set option `saveEmojisAs: 'image'` (EmojioneArea v3.0.0 and higher), 
this will save all emojis as `<img>`, but then you have to save outputs as html in db and take care of injections.
```js
$(".selector").emojioneArea({
    saveEmojisAs: "image"
});
```

Another way is to use Emojione (this lib loads by EmojioneArea, but you can load it manually) 
```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/emojione/2.1.4/lib/js/emojione.min.js"></script>
```

use this style:

```css
.emojione {
    font-size: inherit;
    height: 2ex;
    width: 2.1ex;
    min-height: 20px;
    min-width: 20px;
    display: inline-block;
    margin: -.2ex .15em .2ex;
    line-height: normal;
    vertical-align: middle;
    max-width: 100%;
    top: 0;
    background-image: none;
}
```

and use similar to this code 

```js
$(document).ready(function() {
    // if you save to database with default value of EmojioneArea saveEmojisAs: 'unicode'
    $(".your-selector-with-unicode-emojis").each(function() {
        $(this).html(emojione.unicodeToImage($(this).html()));
    });

    // if you save to db with value EmojioneArea saveEmojisAs: 'shortname'
    $(".your-selector-with-shortname-emojis").each(function() {
        $(this).html(emojione.shortnameToImage($(this).html()));
    });
});
```

[See example here](https://jsfiddle.net/1v03Lqnu/8/).
