### ISSUE TITLE
How to disable injecting emojione.sprites.css 2

### ISSUE THREAD

**Issue by Oranakia** [mervick/emojionearea#223]
I’m having the same issue as the one addressed in #134, however, I’m not being so lucky with the solution.
While attempting to use emojionearea and emojione simultaneously I get the following result.
![emojione](https://user-images.githubusercontent.com/34228199/34644042-fa379f26-f30d-11e7-934e-6c00c3e52b00.png)

https://jsfiddle.net/ukLaz8cm/96/

**Comment by mervick** [comment]
Add this
```
img.emojione {
  background: none!important; 
}
```
https://jsfiddle.net/ukLaz8cm/118/

**Comment by Oranakia** [comment]
Thanks!!! My only remaining issue would be the fact that when the background image gets loaded, the emoji is still resized.
Is there any way to reset/change the new emoji size to be the same as the text?
And thanks again!!!

**Comment by mervick** [comment]
This issues related to `emojione` default style, for avoid this you can use this (from emojionearea)

```css
img.emojione {
  background: none!important; 
  font-size: inherit;
  height: 2ex;
  width: 2.1ex;
  min-height: 20px;
  min-width: 20px;
  display: inline-block;
  margin: -.2ex .15em .2ex;
  line-height: normal;
  vertical-align: middle;
  max-width: 100%;
  top: 0;
}
```
https://jsfiddle.net/ukLaz8cm/120/
