### ISSUE TITLE
Long placeholder text allows the content to overlap the emoji

### ISSUE THREAD

**Issue by Gira-X** [mervick/emojionearea#392]
Without a placeholder, this issue does not occur and the content wraps correctly, respecting the emoji button.

Browser: Firefox

See https://jsfiddle.net/1v03Lqnu/

![Screen Shot 2020-03-16 at 14 58 48](https://user-images.githubusercontent.com/15002298/76765470-5c503a00-678e-11ea-8de6-2af77fb376b9.png)

**Comment by mervick** [comment]
The quick way to fix that is to add this css in your stylesheet
```css
.emojionearea .emojionearea-editor:not(.inline) {
    overflow-wrap: break-word!important;
}
```
