### ISSUE TITLE
Change emojionearea-picker icon image by smiley font

### ISSUE THREAD

**Issue by jsmitjans** [mervick/emojionearea#393]
Hello mervick,Is there any way I can replace the emoticon icon that opens the picker with an emoji icon font? The problem is that I am working on a website that has 2 themes, one dark and one light, and in the dark theme I need the background of the textarea to be black, but when I change the color, then the emoji picker icon is not looks good.Thanks in advance

**Comment by mervick** [comment]
For quick fix you can invert colors in css
```css
.emojionearea .emojionearea-button {
  -webkit-filter: invert(100%) hue-rotate(180deg) contrast(90%) !important;
  filter: invert(100%) hue-rotate(180deg) contrast(90%) !important;
}
```
Example:
https://jsfiddle.net/mervick/m8cqLdrj/4/

If you don't like that, you can change it by modifying css
