### ISSUE TITLE
Emojis are not presented correctly when published

### ISSUE THREAD

**Issue by JWaldenback** [mervick/emojionearea#65]
Hi!

First and foremost I want to thank you for this great emoji picker plugin. You're doing a great job!

I'm having trouble with emojis being presented the wrong way when published. In the editor they look fine but when I publish the message there is another emoji (the old lady) behind each and every emoji.

![image](https://cloud.githubusercontent.com/assets/19432538/19715940/0e2cec38-9b59-11e6-8c3a-36b5b22625d5.png)

**Comment by mervick** [comment]
Hi, try to use custom stylesheets, like below 
```css
body .emojione {
  font-size: inherit;
  height: 2ex;
  width: 2.1ex;
  min-height: 20px;
  min-width: 20px;
  display: inline-block;
  margin: -.2ex .15em .2ex;
  line-height: normal;
  vertical-align: middle;
  max-width: 100%;
  top: 0;
  background-image: none;
}
```
preview https://jsfiddle.net/1v03Lqnu/136/
